# This is a basic workflow to help you get started with Actions

name: detekt

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  detekt:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: detekt
        run: ./gradlew detekt
