# This is a basic workflow to help you get started with Actions

name: detekt

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  detekt:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: detekt
        uses: natiginfo/action-detekt-all@1.16.0-RC1
         #         run: ./gradlew detekt
